project:
  type: book
  output-dir: docs
  resources:
    - LICENSE  # ensures LICENSE is copied to docs/LICENSE

book:
  title: "Including link to license file"
  chapters:
    - index.qmd
  page-footer:
    right:
      # not working
      - text: "Absolute path (fails on GitHub Pages)"
        href: /LICENSE
      # external link works
      - text: "Full URL (works but not ideal)"
        href: https://github.com/julxi/license_in_github_page/blob/main/LICENSE