project:
  type: book        
  output-dir: docs
  execute-dir: project
  resources:
    - LICENSE

book:
  title: "Including link to license file"
  chapters:
    - index.qmd
  page-footer:
    right:
      - text: "Relative path (does not work on github pages)"
        href: /LICENSE
      - text: "Hyperlink (does work on github pages)"
        href: https://github.com/julxi/license_in_github_page/blob/main/LICENSE