project:
  type: book        
  output-dir: docs
  execute-dir: project
  resources:
    - LICENSE

book:
  title: "Including link to license file"
  chapters:
    - index.qmd
  page-footer:
    right:
      - text: "© 2025 Julian Bitterlich · MIT License"
        href: /LICENSE